version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 779846812158.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nodeapp .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag nodeapp:latest 779846812158.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:latest
      - echo Pushing the Docker image to ECR...
      - docker push 779846812158.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:latest

artifacts:
  files:
    - '**/*'
